version: "3.8"

services:
  db:
    image: mariadb
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: visualapproachanalytics
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306

  app:
    build: .
    restart: always
    container_name: app
    ports:
      - 127.0.0.1:5060:5000
    depends_on:
      - db
    volumes:
      - ./:/usr/src/app
    environment:
      - FLASK_APP=wsgi:app
      - FLASK_ENV=development
      - FLASK_DEBUG=1

volumes:
  db_data:
